@host = http://localhost:5050

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "doeJohn@ms.net",
    "password": "doepass"
}

###

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Natasha",
    "lastName": "Atkins",
    "email": "atkinsNat@ms.net",
    "password": "natpass"
}